let name="Darla Sreeramamurthy ManiDeepak"; 
let school="Sri Sarada Vidya Nilayam     "  ;
let grade="  7th                         ";
let section="1B                          ";
let rollno="52                          ";
let maths="  91                          ";
let science="86                          ";
let english="82                          ";
console.log("----------------------------------------");
console.log("|$$$$$$     Report Card          $$$$$$|");
console.log("|Name:", name,                        '|');
console.log("|School:", school,                    '|');
console.log("|Grade:", grade,                      '|');
console.log("|Section:", section,                  '|');
console.log("|Roll No:", rollno,                   '|');
console.log("|Marks obtained in three subjects     ",'|');
console.log("|Maths:", maths,                    '|');
console.log("|Science:", science,                   '|');
console.log("|english:", english,                    '|');
console.log("----------------------------------------");